<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NJDOxq\srcShopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NJDOxq/srcShopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2NJDOxq.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2NJDOxq\srcShopware_Production_KernelDevDebugContainer::class, srcShopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container2NJDOxq\srcShopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '2NJDOxq',
    'container.build_id' => 'e5d379f8',
    'container.build_time' => 1597913376,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NJDOxq');
