<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrV1sPm\srcShopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrV1sPm/srcShopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUrV1sPm.legacy');

    return;
}

if (!\class_exists(srcShopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUrV1sPm\srcShopware_Production_KernelProdContainer::class, srcShopware_Production_KernelProdContainer::class, false);
}

return new \ContainerUrV1sPm\srcShopware_Production_KernelProdContainer([
    'container.build_hash' => 'UrV1sPm',
    'container.build_id' => 'cc948b01',
    'container.build_time' => 1597929123,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrV1sPm');
